image:
  file: .gitpod.Dockerfile

tasks:
  - init: make

vscode:
  extensions:
    - mitaki28.vscode-clang@0.2.3:a5z3DnVxXl8LmAXswnYRtg==
    - cschlosser.doxdocgen@0.7.2:g0DIKlW09t+j2Xi04fzrAA==